// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/noah-labs/wire/cmd/wire
//go:build !wireinject

package main

import (
	"fmt"
)

// Injectors from wire.go:

func injectStringer(s MyString) fmt.Stringer {
	return s
}
